### ISSUE TITLE
Unable to load library mdbx

### ISSUE THREAD

**Issue by xtuyaowu** [castortech/mdbxjni#16]
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [java.lang.LinkageError: Unable to load library mdbx]
	at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:242)
	at org.fusesource.hawtjni.runtime.Library.load(Library.java:194)
	at com.castortech.mdbxjni.JNI.<clinit>(JNI.java:48)
	at com.castortech.mdbxjni.Env.create(Env.java:68)
	at com.castortech.mdbxjni.Env.<init>(Env.java:62)
	at com.daollar.marketdata.app.cobproducer.service.Mdbxjni.init(Mdbxjni.java:52)
	at com.daollar.marketdata.app.cobproducer.service.Mdbxjni.main(Mdbxjni.java:135)
	Suppressed: java.lang.LinkageError: Unable to load library mdbx
		at org.fusesource.hawtjni.runtime.Library.loadLibrary(Library.java:553)
		at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:226)
		... 6 more
	Caused by: java.lang.UnsatisfiedLinkError: no mdbx in java.library.path
		at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
		at java.lang.Runtime.loadLibrary0(Runtime.java:870)
		at java.lang.System.loadLibrary(System.java:1122)
		at org.fusesource.hawtjni.runtime.Library.loadLibrary(Library.java:549)
		... 7 more

thanks !

**Comment by castortech** [comment]
What is happening is that it can't find the library to load. 

Libraries are found in 1 of 3 ways:
1.  via specific properties in the form "library."+name+".path" such as here "library.mdbxjni.path" and "library.mdbx.path"
2. via java LD_LIBARY_PATH
3. via the jar under "META-INF/native/" + os + arch. You have to make sure that the jar is in the classpath and visible to the classloader.

If that doesn't help resolve it, please provide a complete reproducible example so that I can investigate further.

**Comment by xtuyaowu** [comment]
thanks for help
have add to library 
-Djava.library.path=/Users/admin/Documents/workspace/lib/
do you have telegram?

**Comment by castortech** [comment]
I don't have telegram, but please include a reproducible example or link to a github location to such an instance.

**Comment by xtuyaowu** [comment]
I am 100% sure that I have copied the jar to java.library.path but it still gives me an error: Caused by: java.lang.UnsatisfiedLinkError: no mdbx in java.library.path

**Comment by castortech** [comment]
Again please upload a reproducible example. I can provide you in private a secure upload location if you don't want to upload at large.

**Comment by castortech** [comment]
Closing as no reproducible example was provided to reproduce, please provide if you want the issue to be re-opened
